site_name: hyper-surrogate
repo_url: https://github.com/jpsferreira/hyper-surrogate
site_url: https://jpsferreira.github.io/hyper-surrogate
site_description: Hyperelastic Surrogates
site_author: Joao Ferreira
edit_uri: edit/main/docs/
repo_name: jpsferreira/hyper-surrogate
copyright: Maintained by <a href="https://jpsferreira.com">Florian</a>.

nav:
  - Home: index.md
  - Installation: installation.md
  - Modules: modules.md
  - Tutorial1: tutorial1.ipynb
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          collector: griffe
  - mknotebooks
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jpsferreira/hyper-surrogate
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hyper-surrogate

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.magiclink

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/contrib/auto-render.min.js
  - custom.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css
