# Generated by CodiumAI
import numpy as np
from click import Path

from hyper_surrogate.reporter import Reporter


class TestReporter:
    """Test the Reporter class."""

    # The class can be instantiated with a tensor and a save directory.
    def test_instantiation(self):
        tensor = np.random.rand(10, 3, 3)
        save_dir = Path("path/to/save/dir")
        reporter = Reporter(tensor, save_dir)

        assert reporter.tensor.shape == (10, 3, 3)
        assert reporter.save_dir == save_dir

    # The tensor input must be a numpy array with shape (N,3,3).
    def test_tensor_shape(self):
        tensor = np.random.rand(10, 3, 3)
        save_dir = Path("path/to/save/dir")
        reporter = Reporter(tensor, save_dir)
        assert reporter.tensor.shape == (10, 3, 3)
